/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:05:41 GMT 2018
 */

package br.com.ufcg.domain.vo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.ufcg.domain.Especialidade;
import br.com.ufcg.domain.vo.AlterarDadosForm;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AlterarDadosForm_ESTest extends AlterarDadosForm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm("br.com.ufcg.domain.vo.AlterarDadosForm", "br.com.ufcg.domain.vo.AlterarDadosForm", "br.com.ufcg.domain.vo.AlterarDadosForm", (List<Especialidade>) null, "br.com.ufcg.domain.vo.AlterarDadosForm");
      String string0 = alterarDadosForm0.getNovoNomeCompleto();
      assertEquals("br.com.ufcg.domain.vo.AlterarDadosForm", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm("", "PSvl~", "PSvl~", (List<Especialidade>) null, "PSvl~");
      String string0 = alterarDadosForm0.getNovoNomeCompleto();
      assertEquals("PSvl~", alterarDadosForm0.getNovaFotoPerfil());
      assertEquals("", string0);
      assertEquals("PSvl~", alterarDadosForm0.getNovoLogin());
      assertEquals("PSvl~", alterarDadosForm0.getNovoEmail());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm("R,", "R,", "R,", (List<Especialidade>) null, "R,");
      String string0 = alterarDadosForm0.getNovoLogin();
      assertEquals("R,", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm("AD!", "", "br.com.ufcg.domain.vo.AlterarDadosForm", (List<Especialidade>) null, "br.com.ufcg.domain.vo.AlterarDadosForm");
      String string0 = alterarDadosForm0.getNovoLogin();
      assertEquals("br.com.ufcg.domain.vo.AlterarDadosForm", alterarDadosForm0.getNovoEmail());
      assertEquals("", string0);
      assertEquals("AD!", alterarDadosForm0.getNovoNomeCompleto());
      assertEquals("br.com.ufcg.domain.vo.AlterarDadosForm", alterarDadosForm0.getNovaFotoPerfil());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      alterarDadosForm0.setNovoEmail("br.com.ufcg.domain.Especialidade");
      String string0 = alterarDadosForm0.getNovoEmail();
      assertEquals("br.com.ufcg.domain.Especialidade", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      alterarDadosForm0.setNovaFotoPerfil("'SF_bYa~q");
      String string0 = alterarDadosForm0.getNovaFotoPerfil();
      assertEquals("'SF_bYa~q", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      String string0 = alterarDadosForm0.getNovaFotoPerfil();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      List<Especialidade> list0 = alterarDadosForm0.getNovaEspecialidades();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      alterarDadosForm0.setNovaEspecialidades((List<Especialidade>) null);
      assertNull(alterarDadosForm0.getNovaFotoPerfil());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      alterarDadosForm0.setNovoNomeCompleto("AD!");
      assertNull(alterarDadosForm0.getNovaFotoPerfil());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      String string0 = alterarDadosForm0.getNovoNomeCompleto();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm("", "", "", (List<Especialidade>) null, "\"|z||");
      String string0 = alterarDadosForm0.getNovoEmail();
      assertEquals("", alterarDadosForm0.getNovoLogin());
      assertEquals("\"|z||", alterarDadosForm0.getNovaFotoPerfil());
      assertEquals("", string0);
      assertEquals("", alterarDadosForm0.getNovoNomeCompleto());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      String string0 = alterarDadosForm0.getNovoLogin();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      alterarDadosForm0.setNovoLogin("");
      assertNull(alterarDadosForm0.getNovoNomeCompleto());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      alterarDadosForm0.setNovaFotoPerfil("");
      String string0 = alterarDadosForm0.getNovaFotoPerfil();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AlterarDadosForm alterarDadosForm0 = new AlterarDadosForm();
      String string0 = alterarDadosForm0.getNovoEmail();
      assertNull(string0);
  }
}
