/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 12 03:57:08 GMT 2018
 */

package br.com.ufcg.controller;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ServicoController_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "br.com.ufcg.controller.ServicoController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\esNovo\\Trampo"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ServicoController_ESTest_scaffolding.class.getClassLoader() ,
      "br.com.ufcg.domain.Fornecedor",
      "org.springframework.data.repository.query.Param",
      "br.com.ufcg.domain.Usuario",
      "org.springframework.beans.factory.annotation.Autowired",
      "br.com.ufcg.dao.ServicoDAO",
      "org.springframework.data.annotation.QueryAnnotation",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "br.com.ufcg.controller.ServicoController",
      "br.com.ufcg.dao.FornecedorDAO",
      "org.springframework.data.repository.Repository",
      "br.com.ufcg.dao.UsuarioDAO",
      "br.com.ufcg.domain.Cliente",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "br.com.ufcg.domain.Servico",
      "org.springframework.stereotype.Repository",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "br.com.ufcg.repository.ServicoRepository",
      "org.springframework.http.HttpHeaders",
      "br.com.ufcg.service.ServicoService",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Example",
      "org.springframework.web.bind.annotation.RestController",
      "org.springframework.data.domain.Slice",
      "org.springframework.http.HttpEntity",
      "org.springframework.data.util.Streamable",
      "br.com.ufcg.domain.enums.TipoUsuario",
      "org.springframework.http.ResponseEntity$HeadersBuilder",
      "org.springframework.data.jpa.repository.JpaRepository",
      "com.fasterxml.jackson.annotation.JsonIgnoreProperties",
      "org.springframework.data.jpa.repository.Query",
      "br.com.ufcg.domain.Endereco",
      "br.com.ufcg.domain.Avaliacao",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.stereotype.Controller",
      "org.springframework.http.ResponseEntity$BodyBuilder",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.stereotype.Service",
      "org.springframework.stereotype.Indexed",
      "org.springframework.util.ObjectUtils",
      "org.springframework.util.MultiValueMap",
      "org.springframework.web.bind.annotation.ResponseBody",
      "br.com.ufcg.service.ServicoService$1",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.http.HttpStatus",
      "br.com.ufcg.util.response.Response",
      "org.springframework.stereotype.Component",
      "br.com.ufcg.domain.enums.TipoStatus",
      "org.springframework.http.ResponseEntity",
      "org.springframework.util.Assert"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("br.com.ufcg.domain.Servico", false, ServicoController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("br.com.ufcg.repository.ServicoRepository", false, ServicoController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("javax.servlet.http.HttpServletRequest", false, ServicoController_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ServicoController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "br.com.ufcg.controller.ServicoController",
      "org.springframework.web.bind.annotation.RequestMethod",
      "org.springframework.http.HttpStatus",
      "org.hibernate.annotations.FetchMode",
      "com.fasterxml.jackson.annotation.OptBoolean",
      "com.fasterxml.jackson.annotation.JsonFormat$Shape",
      "br.com.ufcg.service.ServicoService",
      "br.com.ufcg.util.response.Response",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.Assert",
      "org.springframework.http.HttpEntity",
      "org.springframework.http.ResponseEntity",
      "br.com.ufcg.domain.Usuario",
      "br.com.ufcg.domain.Cliente",
      "br.com.ufcg.domain.enums.TipoUsuario",
      "br.com.ufcg.service.ServicoService$1",
      "br.com.ufcg.domain.Fornecedor",
      "br.com.ufcg.domain.Endereco",
      "br.com.ufcg.domain.Servico",
      "br.com.ufcg.dao.ServicoDAO",
      "br.com.ufcg.dao.UsuarioDAO",
      "br.com.ufcg.dao.ClienteDAO",
      "br.com.ufcg.util.validadores.ServicoValidador",
      "org.springframework.data.domain.ExampleMatcher$StringMatcher",
      "br.com.ufcg.dao.FornecedorDAO",
      "br.com.ufcg.domain.Especialidade",
      "org.apache.juli.logging.LogFactory",
      "org.apache.juli.logging.DirectJDKLog",
      "org.apache.tomcat.util.res.StringManager",
      "org.apache.tomcat.util.res.StringManager$1",
      "org.apache.coyote.http2.AbstractStream",
      "org.apache.coyote.http2.HeaderSink",
      "org.apache.coyote.http2.Http2UpgradeHandler",
      "br.com.ufcg.domain.Avaliacao",
      "org.springframework.util.ObjectUtils"
    );
  }
}
