/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:07:47 GMT 2018
 */

package br.com.ufcg.domain.vo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.ufcg.domain.vo.LoginForm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoginForm_ESTest extends LoginForm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoginForm loginForm0 = new LoginForm();
      loginForm0.setSenha("`rEl],u&jdP,+BgILR`");
      String string0 = loginForm0.getSenha();
      assertEquals("`rEl],u&jdP,+BgILR`", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoginForm loginForm0 = new LoginForm();
      loginForm0.setSenha("");
      String string0 = loginForm0.getSenha();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LoginForm loginForm0 = new LoginForm();
      loginForm0.setLogin("`rEl],u&jdP,+BgILR`");
      String string0 = loginForm0.getLogin();
      assertEquals("`rEl],u&jdP,+BgILR`", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LoginForm loginForm0 = new LoginForm();
      loginForm0.setLogin("");
      String string0 = loginForm0.getLogin();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LoginForm loginForm0 = new LoginForm();
      String string0 = loginForm0.getLogin();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LoginForm loginForm0 = new LoginForm();
      String string0 = loginForm0.getSenha();
      assertNull(string0);
  }
}
