/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:09:52 GMT 2018
 */

package br.com.ufcg.util.response;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.ufcg.util.response.Response;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Response_ESTest extends Response_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Response response0 = new Response("", integer0, integer0);
      response0.setMessage((String) null);
      String string0 = response0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Response response0 = new Response();
      response0.setMessage("vS?8EzKL94!na)_F8");
      String string0 = response0.getMessage();
      assertEquals("vS?8EzKL94!na)_F8", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Response response0 = new Response();
      Object object0 = response0.getData();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Response response0 = new Response();
      response0.setData("");
      assertNull(response0.getMessage());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(275);
      Response response0 = new Response("5}p(", integer0);
      assertEquals("5}p(", response0.getMessage());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Response response0 = new Response();
      Integer integer0 = new Integer((-1979));
      response0.getStatus(integer0);
      assertNull(response0.getMessage());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Response response0 = new Response("");
      assertEquals("", response0.getMessage());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Response response0 = new Response("", integer0, integer0);
      response0.setStatus(integer0);
      assertEquals("", response0.getMessage());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Response response0 = new Response("", integer0, integer0);
      Object object0 = response0.getData();
      assertEquals(0, object0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Response response0 = new Response("", integer0, integer0);
      String string0 = response0.getMessage();
      assertEquals("", string0);
  }
}
