/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:08:48 GMT 2018
 */

package br.com.ufcg.dao;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.ufcg.dao.ClienteDAO;
import br.com.ufcg.domain.enums.TipoUsuario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClienteDAO_ESTest extends ClienteDAO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoUsuario tipoUsuario0 = TipoUsuario.FORNECEDOR;
      ClienteDAO clienteDAO0 = null;
      try {
        clienteDAO0 = new ClienteDAO((Long) null, "U+<k0JF7$HW*[Rp:", "U+<k0JF7$HW*[Rp:", "w%W", "RM", tipoUsuario0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.ufcg.dao.ClienteDAO", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Long long0 = new Long((-1L));
      TipoUsuario tipoUsuario0 = TipoUsuario.FORNECEDOR;
      ClienteDAO clienteDAO0 = new ClienteDAO(long0, "", "C;{}Epb--", "C;{}Epb--", "C;{}Epb--", tipoUsuario0);
      assertEquals((-1L), (long)clienteDAO0.getId());
  }
}
