/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:07:12 GMT 2018
 */

package br.com.ufcg.dao;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.ufcg.dao.FornecedorDAO;
import br.com.ufcg.domain.Especialidade;
import br.com.ufcg.domain.enums.TipoUsuario;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FornecedorDAO_ESTest extends FornecedorDAO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoUsuario tipoUsuario0 = TipoUsuario.CLIENTE;
      FornecedorDAO fornecedorDAO0 = null;
      try {
        fornecedorDAO0 = new FornecedorDAO((Long) null, "br.com.ufcg.domain.Especialidade", "br.com.ufcg.domain.Especialidade", "br.com.ufcg.domain.Especialidade", "br.com.ufcg.dao.FornecedorDAO", tipoUsuario0, (List<Especialidade>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.ufcg.dao.FornecedorDAO", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Long long0 = new Long(430L);
      TipoUsuario tipoUsuario0 = TipoUsuario.FORNECEDOR;
      FornecedorDAO fornecedorDAO0 = new FornecedorDAO(long0, "{QufwUq~suBvh@", "{QufwUq~suBvh@", "{QufwUq~suBvh@", "{QufwUq~suBvh@", tipoUsuario0, (List<Especialidade>) null);
      fornecedorDAO0.setListaEspecialidades((List<Especialidade>) null);
      assertEquals(TipoUsuario.FORNECEDOR, fornecedorDAO0.getTipo());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Long long0 = new Long(0L);
      TipoUsuario tipoUsuario0 = TipoUsuario.FORNECEDOR;
      FornecedorDAO fornecedorDAO0 = new FornecedorDAO(long0, "y]rYcWr:4(!Mc9_", "y]rYcWr:4(!Mc9_", "y]rYcWr:4(!Mc9_", "y]rYcWr:4(!Mc9_", tipoUsuario0, (List<Especialidade>) null);
      List<Especialidade> list0 = fornecedorDAO0.getListaEspecialidades();
      assertNull(list0);
  }
}
