/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 12 03:51:59 GMT 2018
 */

package br.com.ufcg.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class EspecialidadeService_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "br.com.ufcg.service.EspecialidadeService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\esNovo\\Trampo"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(EspecialidadeService_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.data.repository.query.Param",
      "org.springframework.data.domain.ExampleMatcher$PropertySpecifier",
      "org.springframework.util.ConcurrentReferenceHashMap$Reference",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.data.annotation.QueryAnnotation",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "org.springframework.data.domain.Sort$Direction",
      "org.springframework.data.domain.ExampleMatcher$MatchMode",
      "org.springframework.data.util.LazyStreamable",
      "org.springframework.data.repository.Repository",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment$1",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "org.springframework.core.io.support.SpringFactoriesLoader",
      "org.springframework.stereotype.Repository",
      "br.com.ufcg.domain.Especialidade",
      "org.springframework.data.domain.ExampleMatcher$GenericPropertyMatcher",
      "org.springframework.util.ConcurrentReferenceHashMap$WeakEntryReference",
      "org.springframework.core.io.Resource",
      "org.springframework.data.util.ProxyUtils$ProxyDetector",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "org.springframework.data.domain.PageRequest",
      "org.springframework.util.ConcurrentReferenceHashMap$EntryIterator",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Example",
      "org.springframework.data.domain.TypedExample",
      "org.springframework.data.domain.Slice",
      "org.springframework.data.domain.Sort$NullHandling",
      "org.springframework.data.domain.ExampleMatcher$NoOpPropertyValueTransformer",
      "org.springframework.data.domain.ExampleMatcher$MatcherConfigurer",
      "org.springframework.data.util.Streamable",
      "org.springframework.data.domain.ExampleMatcher$StringMatcher",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.data.domain.TypedExampleMatcher",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.data.domain.Unpaged",
      "org.springframework.data.domain.ExampleMatcher$GenericPropertyMatchers",
      "org.springframework.data.jpa.repository.JpaRepository",
      "com.fasterxml.jackson.annotation.JsonIgnoreProperties",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.data.jpa.repository.Query",
      "org.springframework.util.ConcurrentReferenceHashMap$EntrySet",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "br.com.ufcg.service.EspecialidadeService",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.data.repository.NoRepositoryBean",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "br.com.ufcg.repository.EspecialidadeRepository",
      "org.springframework.data.domain.ExampleMatcher$PropertySpecifiers",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.stereotype.Service",
      "org.springframework.stereotype.Indexed",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$2",
      "org.springframework.util.ConcurrentReferenceHashMap$3",
      "org.springframework.util.ConcurrentReferenceHashMap$4",
      "org.springframework.util.ObjectUtils",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.springframework.util.MultiValueMap",
      "org.springframework.data.util.ProxyUtils",
      "org.springframework.data.domain.ExampleMatcher",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.data.domain.ExampleMatcher$PropertyValueTransformer",
      "org.springframework.stereotype.Component",
      "org.springframework.util.ConcurrentReferenceHashMap$5",
      "org.springframework.data.domain.ExampleMatcher$NullHandler",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("br.com.ufcg.repository.EspecialidadeRepository", false, EspecialidadeService_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(EspecialidadeService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "br.com.ufcg.service.EspecialidadeService",
      "br.com.ufcg.domain.Especialidade",
      "org.springframework.data.domain.TypedExampleMatcher",
      "org.springframework.data.domain.ExampleMatcher$StringMatcher",
      "org.springframework.data.domain.ExampleMatcher$PropertySpecifiers",
      "org.springframework.data.domain.ExampleMatcher$MatchMode",
      "org.springframework.data.domain.TypedExample",
      "org.springframework.util.Assert",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.data.domain.PageRequest",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.util.StringUtils",
      "org.springframework.data.domain.Unpaged",
      "org.springframework.util.ObjectUtils",
      "org.springframework.data.domain.ExampleMatcher$PropertySpecifier",
      "org.springframework.data.util.LazyStreamable",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.core.io.support.SpringFactoriesLoader",
      "org.springframework.data.util.ProxyUtils",
      "org.springframework.data.domain.ExampleMatcher$GenericPropertyMatcher",
      "org.springframework.data.domain.ExampleMatcher$NoOpPropertyValueTransformer"
    );
  }
}
