/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:09:36 GMT 2018
 */

package br.com.ufcg.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import br.com.ufcg.domain.Avaliacao;
import br.com.ufcg.domain.Servico;
import br.com.ufcg.dto.AvaliacaoDTO;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AvaliacaoDTO_ESTest extends AvaliacaoDTO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Avaliacao avaliacao0 = mock(Avaliacao.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(avaliacao0).toString();
      Servico servico0 = mock(Servico.class, new ViolatedAssumptionAnswer());
      AvaliacaoDTO avaliacaoDTO0 = new AvaliacaoDTO(avaliacao0, servico0);
      Avaliacao avaliacao1 = avaliacaoDTO0.getAvaliacao();
      assertEquals(0.0, avaliacao1.getNota(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AvaliacaoDTO avaliacaoDTO0 = new AvaliacaoDTO((Avaliacao) null, (Servico) null);
      avaliacaoDTO0.setAvaliacao((Avaliacao) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AvaliacaoDTO avaliacaoDTO0 = new AvaliacaoDTO((Avaliacao) null, (Servico) null);
      avaliacaoDTO0.setServico((Servico) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AvaliacaoDTO avaliacaoDTO0 = new AvaliacaoDTO((Avaliacao) null, (Servico) null);
      Servico servico0 = avaliacaoDTO0.getServico();
      assertNull(servico0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AvaliacaoDTO avaliacaoDTO0 = new AvaliacaoDTO((Avaliacao) null, (Servico) null);
      Avaliacao avaliacao0 = avaliacaoDTO0.getAvaliacao();
      assertNull(avaliacao0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AvaliacaoDTO avaliacaoDTO0 = new AvaliacaoDTO();
  }
}
