/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:10:38 GMT 2018
 */

package br.com.ufcg.domain.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.ufcg.domain.enums.TipoStatus;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TipoStatus_ESTest extends TipoStatus_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoStatus[] tipoStatusArray0 = TipoStatus.values();
      assertEquals(4, tipoStatusArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TipoStatus tipoStatus0 = TipoStatus.valueOf("CANCELADO");
      assertEquals(TipoStatus.CANCELADO, tipoStatus0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TipoStatus tipoStatus0 = TipoStatus.EM_ABERTO;
      String string0 = tipoStatus0.getTipo();
      assertEquals("Aberto", string0);
  }
}
