/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 12 04:04:54 GMT 2018
 */

package br.com.ufcg.controller;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class AvaliacaoController_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "br.com.ufcg.controller.AvaliacaoController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Thiago\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Thiago\\Documents\\esNovo\\Trampo"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Thiago"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Thiago"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AvaliacaoController_ESTest_scaffolding.class.getClassLoader() ,
      "br.com.ufcg.domain.Fornecedor",
      "br.com.ufcg.domain.Usuario",
      "br.com.ufcg.domain.Avaliacao",
      "br.com.ufcg.controller.AvaliacaoController",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.beans.factory.annotation.Autowired",
      "br.com.ufcg.dao.ServicoDAO",
      "br.com.ufcg.domain.vo.AlterarDadosForm",
      "org.springframework.stereotype.Controller",
      "org.springframework.http.ResponseEntity$BodyBuilder",
      "br.com.ufcg.domain.vo.NovaSenhaForm",
      "br.com.ufcg.service.UsuarioService",
      "org.springframework.stereotype.Service",
      "br.com.ufcg.dao.UsuarioDAO",
      "br.com.ufcg.domain.Cliente",
      "org.springframework.stereotype.Indexed",
      "br.com.ufcg.domain.Servico",
      "br.com.ufcg.domain.Especialidade",
      "org.springframework.http.HttpHeaders",
      "br.com.ufcg.service.ServicoService",
      "org.springframework.util.MultiValueMap",
      "org.springframework.web.bind.annotation.ResponseBody",
      "org.springframework.web.bind.annotation.RestController",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.HttpStatus",
      "br.com.ufcg.dto.AvaliacaoDTO",
      "org.springframework.http.HttpEntity",
      "br.com.ufcg.util.response.Response",
      "org.springframework.stereotype.Component",
      "br.com.ufcg.service.AvaliacaoService",
      "br.com.ufcg.domain.enums.TipoUsuario",
      "org.springframework.http.ResponseEntity",
      "org.springframework.http.ResponseEntity$HeadersBuilder",
      "org.springframework.util.Assert"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("br.com.ufcg.dto.AvaliacaoDTO", false, AvaliacaoController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("br.com.ufcg.service.AvaliacaoService", false, AvaliacaoController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("br.com.ufcg.service.ServicoService", false, AvaliacaoController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("br.com.ufcg.service.UsuarioService", false, AvaliacaoController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("javax.servlet.http.HttpServletRequest", false, AvaliacaoController_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AvaliacaoController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "br.com.ufcg.controller.AvaliacaoController",
      "org.springframework.http.HttpStatus",
      "br.com.ufcg.service.AvaliacaoService",
      "br.com.ufcg.service.ServicoService",
      "br.com.ufcg.service.UsuarioService",
      "br.com.ufcg.util.response.Response",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.Assert",
      "org.springframework.http.HttpEntity",
      "org.springframework.http.ResponseEntity",
      "br.com.ufcg.dto.AvaliacaoDTO",
      "br.com.ufcg.domain.Usuario",
      "br.com.ufcg.domain.Avaliacao"
    );
  }
}
