/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:08:32 GMT 2018
 */

package br.com.ufcg.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.ufcg.controller.InitialController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InitialController_ESTest extends InitialController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InitialController initialController0 = new InitialController();
      String string0 = initialController0.index();
      assertEquals("Hello World!", string0);
  }
}
