/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 04:11:24 GMT 2018
 */

package br.com.ufcg.domain.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.ufcg.domain.enums.TipoUsuario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TipoUsuario_ESTest extends TipoUsuario_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoUsuario[] tipoUsuarioArray0 = TipoUsuario.values();
      assertEquals(2, tipoUsuarioArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TipoUsuario tipoUsuario0 = TipoUsuario.valueOf("CLIENTE");
      assertEquals(TipoUsuario.CLIENTE, tipoUsuario0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TipoUsuario tipoUsuario0 = TipoUsuario.FORNECEDOR;
      Integer integer0 = tipoUsuario0.getTipo();
      assertEquals(1, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TipoUsuario tipoUsuario0 = TipoUsuario.CLIENTE;
      Integer integer0 = tipoUsuario0.getTipo();
      assertEquals(0, (int)integer0);
  }
}
